### ISSUE TITLE
Two different iOS devices logged into the same iCloud account are returning the same UDID.

### ISSUE THREAD

**Issue by cromyun** [GigaDroid/flutter_udid#54] opened 2024-11-11 06:27 UTC
When generating a UDID on iOS devices, if the devices are logged into the same iCloud account, the same UDID is returned. 
Is this intended behavior? 

How can I generate a unique UDID for each device, regardless of the iCloud account?

**Comment by GigaDroid** [comment] 2024-11-11 09:19
Hey, yes this is intended behaviour at the moment to be able to persist the UDID across reinstalls.
I'm closing this for now, as it's a duplicate of #33. Open to reviewing any PRs to implement something like this!

**Closed by GigaDroid** 2024-11-11 09:19 UTC
